spring:
    datasource:
        url: jdbc:h2:mem:tekkenreborn
        generated-unique-name: false


# added database into our application
# also can be done by spring.datasource.name=tekkenreborn
# Note: Here, we have provided datasource url tekkenreborn but it is also not mandatory it is just for presentation purposes and for simplicity as a new url will be genereated everytime so to make it stable we have to provide database url.
# spring.datasource.url=jdbc:h2:mem:tekkenreborn
# spring.datasource.generate-unique-name=false
