package com.cpan252.tekkenreborn.model;

import java.math.BigDecimal;
import java.time.LocalDate;

import com.cpan252.tekkenreborn.model.dto.CreateFighter;
import com.fasterxml.jackson.annotation.JsonValue;

// import org.springframework.data.annotation.Id; this annotation we used with jdbc

// import jakarta.annotation.Generated;
// import org.springframework.data.relational.core.mapping.Table;
// Jakarta is essentially newer version of Java, it is eclipse affiliated company that purchases Java  enterprise. 
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;    // for jpa we have to use this annotation for id.
import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin; 
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data   
@Builder
/*In this class we design the basic model of our fighter
 * Here we define which attributes we want like name, damagePerHit etc.
*/
// @Table
/*
 * @Table, @Id annotations are from Spring Data Package and are useful.
 * By using the @Table an we are telling Spring data to map the table name to actual table
 * We are telling we have a dataabase with a Fighter Table and please consider this class as a model for figher table. 
 */
/*
 * @Entity is a JPA annotation to make this object ready for storage in JPA based data store.
 * @Id is a JPA annotation to make this field the primary key for this object.
 */

@AllArgsConstructor
@NoArgsConstructor
//jakarta == javax
// By using the @Table annotation, we are telling Spring Data to map the table
// name to the table
/**
 * @Entity is a JPA annotation to make this object ready for storage in a JPA based data store. (required)
 * @Id is a JPA annotation to make this field the primary key for this object. (required)
 * @GeneratedValue is a JPA annotation to make this field auto-generated by the JPA provider (required).
 * We also have to have no argument constructor for object to be created by JPA.
 */
@Entity
public class Fighter {

    @Id // We mark id field within id annotation and it is very useful for us because database table needs a primary key which is id.
    // Here we added annotations like @NotBlank, @Max, @Min, @DecimalMin, @DecimalMax because we want to do validation so that user enters the correct value only.
    // Using JPA, we have to provide correct @Id annotation and use @GeneratedValue to auto-generate the id, see the imports.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // it is imported for the database.
    @NotBlank
    private String name;
    @Max(100)
    private int damagePerHit;
    @Min(1000)  
    private int health;
    @DecimalMin(value = "0.1", inclusive = true)
    @DecimalMax(value = "10.0", inclusive= true)
    private BigDecimal resistance; 
    /*This one here, it is used to provide options to select from a option
    * As we want fighters from different animes so we have defined enum so that we can choose characters from multiple animes.
     */ 
    private Anime animeFrom;

    // private final Date createdAt = new Date();
    //We need to create a time stamp but if we use builder and we set thing by default and not provided when we actually the constructing the object then it just ignores LocalDateTime field. IF we provide @Builder.Default it fills the set by default in the builder.  
    
    @Builder.Default
    private LocalDate createdAt =  LocalDate.now();

    public enum Anime{   //defined enum
        NARUTO("Naruto"), BLEACH("Bleach"), ONE_PIECE("One Piece"), TEKKEN("Tekken");    // Defined different animes

        @JsonValue
        private String title;

        // its like a constructor
        private Anime(String title){
            this.title = title;
        }

        // its a getter which returns the value.
        public String getTitle(){
            return title;
        }
    }
    
}
